"""build_items.py — generate equipment.py from the Economics of the Realm CSVs.

The campaign's priced goods live as category CSVs in ./economics_csv/ (the same
data the Economics book renders). This joins the purchasable ones into a single
structured item catalog the character builder can shop from — with the extra
columns the derived sheet needs: armor AC bonus, and weapon damage/speed/etc.

Prices are in copper pieces (cp); 1 gp = 100 cp, 1 sp = 10 cp. Re-run whenever a
source CSV changes:

    python build_items.py

Like build_nwp_book.py / build_spells.py, this is a one-shot generator, not part
of the running app.
"""
import csv
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
CSV_DIR = HERE / "economics_csv"
OUT = HERE / "equipment.py"

CP_PER_GP = 100
CP_PER_SP = 10

# Source file -> display category. Files not listed (Jobs, Services, Inn_Costs,
# Metals — pricing/service tables — plus the malformed Spell_Components legend and
# the under-construction Magic_Tools) are skipped: they aren't carriable goods.
CATEGORIES = {
    "Armor_-_Partial": "Armor",
    "Weapons": "Weapon",
    "Gear": "Gear",
    "Clothing": "Clothing",
    "Food": "Food",
    "Alchemy": "Alchemy",
    "Animal_Gear": "Animal Gear",
    "Animals": "Animals",
    "Transpo": "Transport",
    "Blackmarket": "Black Market",
}
# Display order for the shop.
CATEGORY_ORDER = ["Armor", "Weapon", "Gear", "Clothing", "Food", "Alchemy",
                  "Animal Gear", "Animals", "Transport", "Black Market"]


def _find(header, *needles):
    """Index of the first column whose (lowercased) header contains all needles."""
    for i, h in enumerate(header):
        hl = (h or "").lower()
        if all(n in hl for n in needles):
            return i
    return None


def _cell(row, idx):
    if idx is None or idx >= len(row):
        return ""
    return (row[idx] or "").strip()


def _to_cp(s):
    s = (s or "").replace(",", "").strip()
    if not s:
        return None
    m = re.match(r"-?\d+", s)
    return int(m.group()) if m else None


def _to_float(s):
    s = (s or "").replace(",", "").strip()
    if not s:
        return None
    try:
        return float(s)
    except ValueError:
        return None


def parse_file(path, category):
    rows = list(csv.reader(path.open(newline="", encoding="utf-8-sig")))
    if not rows:
        return []
    header = rows[0]
    name_i = 0
    cost_i = _find(header, "cost")
    weight_i = _find(header, "weight")
    notes_i = _find(header, "note")
    if cost_i is None:
        print(f"  SKIP {path.name}: no Cost column")
        return []

    ac_i = _find(header, "ac") if category == "Armor" else None
    wcols = {}
    if category == "Weapon":
        for key, needle in [("damage", "damage"), ("speed", "speed"), ("type", "type"),
                            ("size", "size"), ("reach", "reach"), ("range", "range")]:
            wcols[key] = _find(header, needle)

    items = []
    for row in rows[1:]:
        name = _cell(row, name_i)
        cost = _to_cp(_cell(row, cost_i))
        if not name or cost is None:
            continue                      # drop legend rows / incomplete entries
        item = {
            "name": name, "category": category, "cost_cp": cost,
            "weight": _to_float(_cell(row, weight_i)),
            "notes": _cell(row, notes_i),
        }
        if category == "Armor":
            item["ac_bonus"] = _to_cp(_cell(row, ac_i)) or 0
        if category == "Weapon":
            for key, idx in wcols.items():
                item[key] = _cell(row, idx)
        items.append(item)
    return items


def emit(items):
    lines = [
        '"""equipment.py — AUTO-GENERATED by build_items.py. Do not edit by hand.',
        "",
        "The campaign's purchasable goods (Economics of the Realm), joined into one",
        "structured catalog for the character builder. Prices are copper pieces (cp).",
        "Regenerate with `python build_items.py`.",
        '"""',
        f"CP_PER_GP = {CP_PER_GP}",
        f"CP_PER_SP = {CP_PER_SP}",
        f"CATEGORY_ORDER = {CATEGORY_ORDER!r}",
        "",
        "# name, category, cost_cp, weight, notes (+ ac_bonus for armor; damage/speed/… for weapons)",
        "ITEMS = [",
    ]
    for it in items:
        lines.append(f"    {it!r},")
    lines.append("]")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")


def main():
    all_items = []
    per_cat = {}
    for stem, category in CATEGORIES.items():
        path = CSV_DIR / f"{stem}.csv"
        if not path.exists():
            print(f"  MISSING {path.name}")
            continue
        got = parse_file(path, category)
        per_cat[category] = len(got)
        all_items.extend(got)
    emit(all_items)
    print(f"Wrote {OUT.name}: {len(all_items)} items.")
    for cat in CATEGORY_ORDER:
        if cat in per_cat:
            print(f"  {cat}: {per_cat[cat]}")
    armor = [i for i in all_items if i["category"] == "Armor"]
    weap = [i for i in all_items if i["category"] == "Weapon"]
    print(f"  armor with ac_bonus: {sum(1 for a in armor if a.get('ac_bonus'))}/{len(armor)}")
    print(f"  weapons with damage: {sum(1 for w in weap if w.get('damage'))}/{len(weap)}")


if __name__ == "__main__":
    main()
