"""build_splash_assets.py — embed the splash logo + display font as data: URIs.

Generates `splash_assets.py`, holding the campaign's AD&D 2nd Edition logo
(`assets/adnd2e-logo.png`, already matted to a transparent background) and the
Death Star display font (`assets/DeathStar.otf`) as inline `data:` URIs. Baking
them into a module keeps the splash offline the same way `page_images.py` keeps
the rulebook art offline — no network request, and no runtime file access, so it
works identically in dev and in the frozen PyInstaller bundle.

Death Star is © Dennis Ludlow / Sharkshock, free for personal use as long as its
readme stays intact — it ships alongside the font at `assets/DeathStar-readme.txt`.

Run from the repo root:  python scripts/build_splash_assets.py
"""
import base64
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOGO = ROOT / "assets" / "adnd2e-logo.png"
FONT = ROOT / "assets" / "DeathStar.otf"
OUT = ROOT / "splash_assets.py"


def _data_uri(path: Path, mime: str) -> str:
    return f"data:{mime};base64," + base64.b64encode(path.read_bytes()).decode("ascii")


def main() -> None:
    logo = _data_uri(LOGO, "image/png")
    font = _data_uri(FONT, "font/otf")
    OUT.write_text(
        '"""splash_assets.py — GENERATED by scripts/build_splash_assets.py. Do not hand-edit.\n'
        "\n"
        "The splash's logo art and display font as inline data: URIs, so the home\n"
        "screen renders with no network request and no runtime file access. Re-run\n"
        'the build script to change the art or the font."""\n'
        "\n"
        f"LOGO_DATA_URI = {logo!r}\n"
        "\n"
        f"FONT_DATA_URI = {font!r}\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT.name}: logo {len(logo)} chars, font {len(font)} chars")


if __name__ == "__main__":
    main()
